name: Projects

on:
  push:
    branches:
      - release/*
      - projects/*
      - featre/project*
      - develop
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        project:
          - marlin:
            repository: "MarlinFirmware/Marlin"
            folder: Marlin
            envname: "teensy36"
        os: [ubuntu-latest]
        python-version: ["3.7"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/platformio/platformio-core

      - name: Check out ${{ matrix.project.repository }}
        uses: actions/checkout@master
        with:
          repository: ${{ matrix.project.repository }}

      - name: Check out ${{ matrix.project.repository }}
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.project.repository }}
          path: ${{ matrix.project.folder }}

      - name: Compile ${{ matrix.project.repository }}
        run: |
          ls -al
          ls ${{ matrix.project.folder }}
          pio run -d ${{ matrix.project.folder }} -e ${{ matrix.project.envname }}

