name: Projects

on:
  push:
    branches:
      - release/*
      - projects/*
      - featre/project*
      - develop
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        project:
          - marlin:
            repository: "MarlinFirmware/Marlin"
            folder: Marlin
            envname: "teensy36"
        os: [ubuntu-latest]
        python-version: ["3.7"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Check out ${{ matrix.project.repository }}
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          repository: ${{ matrix.project.repository }}
          path: ${{ matrix.project.folder }}

      - name: Configure Marlin target
        # The board is selected the in 'Configuration.h' file
        # Currently, there is no way to pass the board via a build flag -D
        # as there is a prescript that carries out some validations before build step
        if: ${{ matrix.project.repository == 'MarlinFirmware/Marlin' }}
        run: |
          sed -i 's/#define MOTHERBOARD BOARD_RAMPS_14_EFB/#define MOTHERBOARD BOARD_TEENSY35_36/g' ${{ matrix.project.folder }}/Marlin/Configuration.h

      - name: Compile ${{ matrix.project.repository }}
        run: |
          pio run -d ${{ matrix.project.folder }} -e ${{ matrix.project.envname }}

