name: Projects

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        project:
          - marlin:
            repository: "MarlinFirmware/Marlin"
            folder: "Marlin"
            config_dir: "Marlin"
            env_name: "mega2560"
          - esphome:
            repository: "esphome/esphome"
            folder: "esphome"
            config_dir: "esphome"
            env_name: "esp32-arduino"
        os: [ubuntu-latest, windows-latest, macos-latest]
    # Skip ESPHome on Windows
    if: "${{ !(contains(matrix.project.repository, 'esphome') && matrix.os == 'windows-latest') }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Check out ${{ matrix.project.repository }}
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          repository: ${{ matrix.project.repository }}
          path: ${{ matrix.project.folder }}

      - name: Install ESPHome dependencies
        # Requires esptool package as it's used in a custom prescript
        if: ${{ contains(matrix.project.repository, 'esphome') }}
        run: pip install esptool==3.*

      - name: Compile ${{ matrix.project.repository }}
        run: pio run -d ${{ matrix.project.config_dir }} -e ${{ matrix.project.env_name }}

